# Generated by Django 4.0.4 on 2022-06-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_alumni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=100)),
                ('pekerjaan', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=15)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], max_length=10)),
                ('angkatan', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], max_length=10)),
            ],
        ),
    ]
